### ISSUE TITLE
MSpec extensions

### ISSUE THREAD

**Issue by smithmx** [dolittle-boilerplates/home#3]
We should create a project with MSpec extensions that help assert against our specific stuff (e.g. EventStream, ValidationResult, CommandResult, etc)

**Comment by smithmx** [comment]
We've got some old stuff in 

https://github.com/dolittle/Bifrost/tree/master/Source/Bifrost.MSpec

and the CBS UserManagement/Domain.Specs has some Extension methods that I throw together to help.

**Comment by woksin** [comment]
Would be cool to have this soon ;)

**Comment by smithmx** [comment]
Is the CBS stuff missing anything that you think you need?  I can quickly wrap that up if that will help.  The CommandScenario<> stuff from the old Bifrost is a different kettle of fish entirely.  That will take some thought and time.

**Comment by woksin** [comment]
Is not that it's high demand, I just think it would be low-effort high-reward to implement this in the framework, I could even do it

**Comment by einari** [comment]
This is in the wrong place; we should have a new repository under extensions called `Dolittle.Machine.Specifications`.

Over time, if we do more on testing and provide tooling and/or extensions we could consider having our own organization for it to group all the things related to the topic. 

Lets see if the stuff we did for Bifrost still is valid and build and extend on it; https://github.com/dolittle/Bifrost/tree/master/Source/Bifrost.MSpec
